SRC/OnlineShopping/OnlineShopping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('products/', include('product.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('shop/', include('shop.urls', namespace='shop')),
                  path('orders/', include('orders.urls', namespace='orders')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                             document_root=settings.MEDIA_ROOT)

SRC/OnlineShopping/accounts/urls.py
from django.urls import path
from .views import user_login, user_logout, user_register

app_name = 'accounts'
urlpatterns = [
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('register/', user_register, name='register')
]

SRC/OnlineShopping/cart/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'cart'
urlpatterns = [
    path('home/', home, name='home'),
    # just for english slugs
    # path('products/<slug:slug>/', product_detail, name='product_detail'),
    re_path(r'^products/(?P<slug>[-\w]+)/', product_detail, name='product_detail'),
    # just for english slugs
    # path('category/<slug:slug>/', category_filter, name='category_filter'),
    re_path(r'^category/(?P<slug>[-\w]+)/', home, name='category_filter'),

]
# r'^(?P<slug>[^/]+)/$

SRC/OnlineShopping/templates/inc/message.html
{% if messages %}
{% for msg in messages %}
<p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
{% endfor %}
{% endif %}

SRC/OnlineShopping/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'cart:home' %}">Home</a>
        {% if request.user.is_authenticated %}
        <a class="nav-item nav-link active" href="{% url 'accounts:logout' %}">Logout</a>
        {% else %}
        <a class="nav-item nav-link active" href="{% url 'accounts:login' %}">Login</a>
        <a class="nav-item nav-link active" href="{% url 'accounts:register' %}">Register</a>
        {% endif %}

    </div>
</nav>