SRC/OnlineShopping/OnlineShopping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('products/', include('product.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('shop/', include('shop.urls', namespace='shop')),
                  path('orders/', include('orders.urls', namespace='orders')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                             document_root=settings.MEDIA_ROOT)

SRC/OnlineShopping/cart/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'cart'
urlpatterns = [
    path('home/', home, name='home'),
    # just for english slugs
    # path('products/<slug:slug>/', product_detail, name='product_detail'),
    re_path(r'^products/(?P<slug>[-\w]+)/', product_detail, name='product_detail'),
    # just for english slugs
    # path('category/<slug:slug>/', category_filter, name='category_filter'),
    re_path(r'^category/(?P<slug>[-\w]+)/', home, name='category_filter'),

]
# r'^(?P<slug>[^/]+)/$

SRC/OnlineShopping/orders/urls.py
from django.urls import path
from .views import *

app_name = 'orders'
urlpatterns = [
    path('create/', create_order, name='create'),
    path('<int:order_id>/', order_detail, name='detail'),
    path('payment/<int:order_id>/<price>', payment, name='payment'),
    path('verify/', verify, name='verify'),
    path('apply/<int:order_id>/', coupon_apply, name='coupon_apply'),
]

SRC/OnlineShopping/shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'
urlpatterns = [
    # shop/ will render the shopping cart details for us
    path('detail/', detail, name='detail'),
    path('add/<int:product_id>', add_cart, name='add_cart'),
    path('remove/<int:product_id>', remove_cart, name='remove_cart'),

]

SRC/OnlineShopping/shop/models.py
from django.db import models

# Create your models here.

SRC/OnlineShopping/shop/forms.py
from django import forms


class AddForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=10)

SRC/OnlineShopping/shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .shop import Shop
from product.models import Product
from .forms import AddForm
from django.views.decorators.http import require_POST


# Create your views here.
# display the shopping cart detail
def detail(request):
    shop = Shop(request)
    return render(request, 'shop/detail.html', {'shop': shop})


# adding items to cart
# user must access this view by post method
@require_POST
def add_cart(request, product_id):
    shop = Shop(request)
    product = get_object_or_404(Product, id=product_id)
    form = AddForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        shop.add(product, cd['quantity'])
    return redirect('shop:detail')


# remove item from shopping cart
def remove_cart(request, product_id):
    shop = Shop(request)
    product = get_object_or_404(Product, id=product_id)
    shop.remove(product)
    return redirect('shop:detail')

SRC/OnlineShopping/shop/templates/shop/detail.html
{% extends 'base.html' %}
{% block content %}
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Product</th>
        <th scope="col">Quantity</th>
        <th scope="col">Unit Price</th>
        <th scope="col">Total Price</th>
        <th scope="col">Remove Item</th>
    </tr>
    </thead>
    <tbody>
    {% for item in shop %}
    <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{item.product.name}}</td>
        <td>{{item.quantity}}</td>
        <td>{{item.price}}</td>
        <td>{{item.total_price}}</td>
        <td>
            <a href="{% url 'shop:remove_cart' item.product.id %}">
                <button type="button" class="btn-close" aria-label="Close" style="background-color: red"></button>
            </a>
        </td>
    </tr>
    {% endfor %}
    <tr>
        <td>Total</td>
        <td colspan="4"></td>
        <td>{{ shop.get_total_price }}</td>
    </tr>
    </tbody>
</table>
<a class="btn btn-primary" href="{% url 'orders:create' %}">Checkout</a>
{% endblock %}